# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sYFYVJq4--Hpr-tARMVfqkN748VfIjk7
"""

import numpy as np
import plotly.graph_objects as go 
from ipywidgets import FloatSlider, Dropdown
import math
from IPython.display import display

A_1=FloatSlider(value=5.0, min=0.0, max=10.0, step=0.1, description='A_1 [V]:')

Phi_1=FloatSlider(value=0, min=-360.0, max=360.0, step=0.1, description='Phi_1: [deg]')

f_1=FloatSlider(value=10.0, min=0.0, max=20.0, step=0.1, description='f_1: [kHz]')

w_1=FloatSlider(value=50.0, min=0.0, max=100.0, step=0.1, description='w_1: [Rad/s]')

A_2=FloatSlider(value=5.0, min=0.0, max=10.0, step=0.1, description='A_2 [V]:')

Phi_2=FloatSlider(value=0, min=-360.0, max=360.0, step=0.1, description='Phi_2: [deg]')

f_2=FloatSlider(value=10.0, min=0.0, max=20.0, step=0.1, description='f_2: [kHz]')

w_2=FloatSlider(value=50.0, min=0.0, max=100.0, step=0.1, description='w_2: [Rad/s]')

choice = Dropdown(options=['FREQUENCY', 'FUNCTIONS'], value='FREQUENCY', description='Use:')

display(A_1)
display(A_2)
display(Phi_1)
display(Phi_2)
display(f_1)
display(f_2)
display(w_1)
display(w_2)

display(choice)